config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] 
  root 'tweets#index'
  resources :tweets do 
    resources:likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]

  resources :maps, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  mount_uploader :image, ImageUploader
  #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  
  
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
    end
  end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def new
        @tweet = Tweet.new
      end

      def index
        @tweets = Tweet.all
      
        if params[:tag_ids]
          @tweets = []
          params[:tag_ids].each do |key, value|
            if value == "1"
              tag_tweets = Tag.find_by(name: key).tweets
              @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_s
            end
          end
        end

    end  
    
      def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def show
        @tweet = Tweet.find(params[:id])
      end 

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end
    
      private
      def tweet_params
        params.require(:tweet).permit(:name, :genre, :address, :menu, :about, :image, :overall, :lat, :lng, tag_ids:[])
      end
      
     #ここまで

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def getPercent(number) 
        if number.present?
            number = number.to_f
          calPercent = number/5 * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          percent
        else
          0
        end
      end
     
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haruapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c211def1f3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Old+Mincho&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
    <h1><%= link_to "グルメな街「三軒茶屋」", tweets_path %></h1>
    
    <div class="header-list">
      <ul>
      <% if user_signed_in? %>
        <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
      </ul>
      <img src="">

    </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
   </body> 
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<div class="slideshow">
    <div class="slideshow-image" style="background-image: url('<%= asset_path 'santya1' %>');"></div>
    <div class="slideshow-image" style="background-image: url('<%= asset_path 'santya2' %>');"></div>
    <div class="slideshow-image" style="background-image: url('<%= asset_path 'santya3' %>');"></div>
</div>

<%= image_tag 'station.PNG', class:"frog" %>

<div class="chu">
渋谷から田園都市線で二駅、 ネオ居酒屋から老舗まで、、あらゆるジャンルが密集するにぎやかな街。 
</div>

<div class="tag">
   <h1>サンチャ・グルメ</h1>
   <h3>一覧ページ</h3>
   <div class="mypage2">
   <%= link_to "新規投稿へ", new_tweet_path %>
   </div>
   <div class="mypage3">
      <% if user_signed_in? %>  
        <%= link_to "マイページへ", user_path(current_user.id) %>
      <% end %>
  </div>
   <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
      <% Tag.all.each do |t| %>
            <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
      <% end %>
       <%= submit_tag '検索' %>
      <% end %>
 </div>

<div class="tweets-container">
  <% @tweets.each do |t| %>
  <div class="tweet">
    <div class="tweet1">
    <div class="image1">
      <%= image_tag t.image_url, size: "220x200" if t.image? %>
    </div>  
      <p>
      店名：<%= t.name %>
      </p> 
      <p>
      ジャンル：<%= t.genre %>
      </p>
      <p>
      料理名：<%= t.menu %>
      </p>
      <p>
      コメント：<%= t.about %>
      </p>
      <p>
      キーワード：<% t.tags.each do |tag| %>
        <span><%= tag.name %></span>
    <% end %>
    
      </p>
      
        
  
    
      
    <h2>総合評価：
    <span class="star-rating">
      <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
      <span class="star-rating-back">★★★★★</span>
    </span> 
    </h2>

      
        <div class= 'likeButton'>
        <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <i class="fa-solid fa-heart-circle-xmark"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
       <% else %>
       <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
        </div>

    <%= t.created_at %>
    <%= link_to "詳細へ", tweet_path(t.id) %>

    <% if user_signed_in? && current_user.id == t.user_id %>
    <%= link_to "編集する", edit_tweet_path(t.id) %>
    <%= button_to "削除する", tweet_path(t.id), method: :delete %>
    
     <%= link_to t.user.name, user_path(t.user.id) %>
     <%= t.user.email %>
     </div>
        
    <% end %> 
    </div>
     <% end %> 

      

</div>

app/views/tweets/new.html.erb
<h1>SANTYAグルメ</h1>
<div class="sinki">
  <h3>新規投稿</h3>
  <%= form_for @tweet do |f| %>

    <div class="field">
      <%= f.label :店名 %>
      <%= f.text_field :name, :size => 30 %>
    </div>

    <div class="field">
      <%= f.label :ジャンル  %>
      <%= f.select :genre, 
      [["和食", "和食"], 
      ["イタリアン", "イタリアン"], 
      ["中華", "中華"],
      ["韓国料理", "韓国料理"],
      ["スペイン料理", "スペイン料理"],
      ["その他", "その他"]], include_blank: "選択して下さい" %>
    </div>

  <div class="field">
  <%= f.label :注文した料理  %>
  <%= f.text_area :menu, :size => "30x2" %>
  </div>

  <div class="field">
  <%= f.label :口コミ  %>
  <%= f.text_area :about, :size => "30x2" %>
  </div>


  <div class="field">
      <%= f.label :写真 %>
      <%= f.file_field :image %>
  </div>

      <%= f.label :lat,"緯度" %>
      <%= f.text_field :lat, id: :lat %>
      <%= f.label :lng,"経度" %>
      <%= f.text_field :lng, id: :lng %>

      <h5>総合評価</h5>
      <div class="post_form">
      <%= f.radio_button :overall, 5 ,id: 'star1'%>
      <label for="star1"><span class="text">最高</span>★</label>
  
      <%= f.radio_button :overall, 4 ,id: 'star2'%>
      <label for="star2"><span class="text">良い</span>★</label>
  
      <%= f.radio_button :overall, 3 ,id: 'star3'%>
      <label for="star3"><span class="text">普通</span>★</label>
  
      <%= f.radio_button :overall, 2 ,id: 'star4'%>
      <label for="star4"><span class="text">悪い</span>★</label>
  
      <%= f.radio_button :overall, 1 ,id: 'star5'%>
      <label for="star5"><span class="text">最悪</span>★</label>
    </div>

    <h6>タグ</h6>
    <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
                <%= tag.check_box class: 'form-check-input' %>
                <%= tag.text %>
            <% end %>
        </div>
    <% end %>
</div>
  

  <h2>Map</h2>

  <input id="address" type="textbox" value="GeekSalon">
  <input type="button" value="検索" onclick="codeAddress()">
  <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
  <div id='map'></div>

  <style>
  #map {
    height: 600px;
    width: 600px;
  }
  </style>

  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: 35.6803997, lng:139.7690174},  //東京
      zoom: 15,
      
    });
  }

  //検索後のマップ作成
  let geocoder
  let aft
  function codeAddress(){
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode( { 'address': inputAddress}, function(results, status) {
      if (status == 'OK') {
          //マーカーが複数できないようにする
          if (aft == true){
              marker.setMap(null);
          }

          //新しくマーカーを作成する
          map.setCenter(results[0].geometry.location);
              marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location,
              draggable: true	// ドラッグ可能にする
          });

          //二度目以降か判断
          aft = true

          //検索した時に緯度経度を入力する
          document.getElementById('lat').value = results[0].geometry.location.lat();
          document.getElementById('lng').value = results[0].geometry.location.lng();

          // マーカーのドロップ（ドラッグ終了）時のイベント
          google.maps.event.addListener( marker, 'dragend', function(ev){
              // イベントの引数evの、プロパティ.latLngが緯度経度
              document.getElementById('lat').value = ev.latLng.lat();
              document.getElementById('lng').value = ev.latLng.lng();
          });
      } else {
        alert('該当する結果がありませんでした：' + status);
      }
    });   
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0j920Wyxy9Dm3BesRD9fm2gwoT6eci5c&callback=initMap" async defer></script>


  <%= f.submit "投稿する" %>
  <% end %>
  </div>
  <%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>SANTYAグルメ</h1>
<div class="comment">
  <h2>投稿詳細</h2>
    <p>クチコミ：<%= @tweet.about %></p>

    キーワード：
    <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
    <% end %>

  <h3>総合評価：
  <span class="star-rating">
    <span class="star-rating-front" style="width: <%= getPercent(@tweet.overall) %>%;">★★★★★</span>
    <span class="star-rating-back">★★★★★</span>
  </span> 
  </h2>

  <% if user_signed_in? %>
    <% if current_user.already_liked?(@tweet) %>
      <%= button_to tweet_like_path(@tweet), method: :delete do %>
        <i class="fas fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% else %>
      <%= button_to tweet_likes_path(@tweet), method: :post do %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= @tweet.likes.count %>
  <% end %>

  </div>
 
  <div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @tweet.lat %>, lng: <%= @tweet.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @tweet.lat %>, lng: <%= @tweet.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0j920Wyxy9Dm3BesRD9fm2gwoT6eci5c&callback=initMap" async defer></script>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<p><%= @tweet.created_at %></p>

<%= link_to "投稿一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage">
<h1>マイ"SANTYAグルメ"ページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.about %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <p>
  <%= t.user.name %>
  <%= t.about %>
  </p>
<% end %>

</div>
<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= render 'relationships/follow_button', user: @user %>